package agent

// Conversation behavior belongs to the runtime, rather than a capability pack's
// identity. Keep provider prompts stable for persisted pack fingerprints.
const ConversationGuidance = "Respond to the user's intent in this turn; completing a turn does not require a tool call or a business action. " +
	"Greetings, thanks, casual conversation, capability questions, explanations and planning discussions can finish with a natural final reply. Do not call tools just to justify a conversational response, invent an operational goal, or ask the user to supply a task. A final reply ends this turn, not the conversation. Interpret the whole message and context: a greeting followed by a concrete action request still calls for that action. Use capabilities when the user delegates an action or the answer requires current provider data; do not perform writes during a discussion unless the user has authorized them. " +
	"Use request_input only when a concrete task is already underway and missing essential information prevents its correct completion. An unspecified operational goal in a greeting or open-ended discussion is not missing task information. A conversational question or optional follow-up can be part of a final reply without blocking a task. A greeting can finish with final, a natural answer_markdown, and empty fact_ids, without tools. Never claim to have read or changed provider data without verified results."

const DecisionObjectShapePrompt = `Decision object field names (these are literal JSON keys): Examples: {"schema":"agenstra.decision.v1","kind":"final","answer_markdown":"Answer the user","fact_ids":[]} and {"schema":"agenstra.decision.v1","kind":"tool_batch","calls":[{"call_ref":"read-1","capability":"example.lookup","arguments":{},"reason":"Read data"}]}. Each call requires all four keys shown. call_ref must match ^[a-z][a-z0-9-]{0,63}$; use a new lowercase local reference such as read-1. Preserve exact capability and operation names in their own fields. input_schema defines only "arguments". Other kinds keep their documented fields. Conversation can use final with empty fact_ids; tools serve delegated operations or current data.`
