-- Generated by Agenstra Python v0.5.0; non-production compatibility fixture.
BEGIN TRANSACTION;
CREATE TABLE artifacts (
                            run_id TEXT NOT NULL REFERENCES runs(run_id),
                            artifact_id TEXT NOT NULL,
                            payload_json TEXT NOT NULL,
                            sha256 TEXT NOT NULL,
                            PRIMARY KEY (run_id, artifact_id)
                        );
INSERT INTO "artifacts" VALUES('cc673326-fcdd-4f40-bec8-e2f388321ef1','64804d73-c538-41b1-9bbe-deeb29471d46','{"connection_id":null,"expires_at":null,"fact_id":"64804d73-c538-41b1-9bbe-deeb29471d46","observed_at":"2023-11-14T00:00:00Z","quality":"provider_reported","reference_scope":"durable","source_capability":"records.get","source_version":"1","value":{"data":{"count":1.0,"id":"R-1","label":"记录 <A>"}}}','48321bea30d4e7a4cdcd06a7ebc2868cdc5c86ff9191cad19b5e2e6958b3b255');
CREATE TABLE events (
                            sequence INTEGER PRIMARY KEY AUTOINCREMENT,
                            run_id TEXT NOT NULL REFERENCES runs(run_id),
                            created_at REAL NOT NULL,
                            event_json TEXT NOT NULL
                        );
INSERT INTO "events" VALUES(1,'cc673326-fcdd-4f40-bec8-e2f388321ef1',1700000000.0,'{"kind":"model_decided","round":1}');
CREATE TABLE invocations (
                            run_id TEXT NOT NULL REFERENCES runs(run_id),
                            invocation_id TEXT NOT NULL,
                            payload_json TEXT NOT NULL,
                            PRIMARY KEY (run_id, invocation_id)
                        );
CREATE TABLE runs (
                            run_id TEXT PRIMARY KEY,
                            owner_id TEXT NOT NULL,
                            pack_id TEXT NOT NULL,
                            status TEXT NOT NULL,
                            state_json TEXT NOT NULL,
                            revision INTEGER NOT NULL,
                            next_wake_at REAL,
                            lease_token TEXT,
                            lease_until REAL,
                            created_at REAL NOT NULL,
                            updated_at REAL NOT NULL,
                            cancel_requested INTEGER NOT NULL DEFAULT 0
                        );
INSERT INTO "runs" VALUES('cc673326-fcdd-4f40-bec8-e2f388321ef1','alice','records','needs_input','{"artifact_ids":["64804d73-c538-41b1-9bbe-deeb29471d46"],"pack_fingerprint":null,"pack_release":null,"runtime":{"answer_markdown":"","decisions":[],"error_code":null,"followups":[],"input_field":"destination","input_prompt":"Which destination?","inspected_capability":null,"inspected_fact":null,"instruction":"Look up record R-1","loaded_skills":[],"model_observations":[],"observations":[],"pending":[],"poll_calls_used":0,"repeated":{},"rounds_used":0,"run_id":"cc673326-fcdd-4f40-bec8-e2f388321ef1","schema_version":1,"status":"needs_input","tool_calls_used":0,"used_refs":[]}}',1,NULL,NULL,NULL,1700000000.0,1700000000.0,0);
CREATE INDEX runs_due
                            ON runs(status, next_wake_at, lease_until);
CREATE INDEX runs_owner ON runs(owner_id, created_at);
CREATE INDEX events_run ON events(run_id, sequence);
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('events',1);
COMMIT;
PRAGMA user_version=1;
